### ISSUE TITLE
[Pre/Ap]pend newly drawn cards

### ISSUE THREAD

**Issue by klkl85** [conorriches/OnlineMultiplayerUno#2]
New cards are appended to your hand. When drawing large numbers of cards this may cause scrolling to see what the newly drawn card is and if it can be played.

Suggest that newly drawn cards are prepended to your hand so that they’re always visible irrespective of screen or hand size.

**Comment by conorriches** [comment]
Fixed! Thanks for the suggestion. This improves game play
